import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Gabriel: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gabe's app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

  <div>

    <h1 className="colorred">Gabriel Second Page</h1>
  </div>
    </div>
  )
}

export default Gabriel
